name: "Webhook Event example"

on:
  repository_dispatch:
    types:
      - on-demand-test

jobs:
  respond-to-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run a script
        run: |
          echo "This is a webhook event"
          echo "Event of type $GITHUB_EVENT_NAME"
